ALTER TABLE t_p20462627_fresh_vegetable_deli.catalog_overrides
  ADD COLUMN IF NOT EXISTS weight VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS weight_kg NUMERIC(10,3) NULL,
  ADD COLUMN IF NOT EXISTS hidden BOOLEAN NOT NULL DEFAULT FALSE;
